# Generated by Django 4.2.4 on 2023-08-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, verbose_name='Experience')),
                ('completed_rundowns', models.CharField(max_length=200, verbose_name='Completed Rundowns')),
            ],
        ),
    ]
