# Generated by Django 4.2.4 on 2023-08-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prisoner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='password',
            field=models.CharField(default='s3cret', max_length=200),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='username',
            field=models.CharField(default='s', max_length=200, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Experience'),
        ),
    ]
