# Generated by Django 4.2.4 on 2023-08-11 04:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisoner', '0002_prisoner_groups_prisoner_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prisoner',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
