# Generated by Django 4.2.4 on 2023-09-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rundown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('release_date', models.DateField(verbose_name='Release date')),
            ],
            options={
                'verbose_name': 'Rundown',
                'verbose_name_plural': 'Rundowns',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('tier', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Tiers')),
                ('difficulty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('X', 'X')], max_length=1, verbose_name='Difficulty')),
                ('xp', models.PositiveIntegerField(verbose_name='Experience')),
                ('rundown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rundown.rundown', verbose_name='Rundown')),
            ],
            options={
                'verbose_name': 'Expedition',
                'verbose_name_plural': 'Expeditions',
            },
        ),
    ]
