# Generated by Django 4.2.4 on 2023-08-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Experience'),
        ),
    ]
