# Generated by Django 4.2.4 on 2023-08-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0002_expedition_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='xp',
            field=models.PositiveIntegerField(verbose_name='Experience'),
        ),
    ]
