# Generated by Django 4.2.4 on 2023-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0002_expedition_main_sector_expedition_overload_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='sectors',
        ),
        migrations.AlterField(
            model_name='expedition',
            name='main_sector',
            field=models.BooleanField(default=True, verbose_name='Main'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='overload_sector',
            field=models.BooleanField(default=False, verbose_name='Overload'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='secondary_sector',
            field=models.BooleanField(default=False, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='tier',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Tier'),
        ),
    ]
