# Generated by Django 4.2.4 on 2023-09-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0002_expedition_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='display_name',
            field=models.CharField(max_length=4, verbose_name='Display name'),
        ),
    ]
