# Generated by Django 4.2.4 on 2023-09-24 21:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0003_alter_expedition_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='sectors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'MAIN'), ('secondary', 'SECONDARY'), ('overload', 'OVERLOAD')], default=('main', 'MAIN'), max_length=9, verbose_name='Sectors'),
        ),
    ]
