# Generated by Django 4.2.4 on 2023-09-24 22:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0009_alter_expedition_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='sectors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Main', 'Main'), ('Secondary', 'Secondary'), ('Overload', 'Overload')], default='Main', max_length=23, verbose_name='Sectors'),
        ),
    ]
