# Generated by Django 4.2.4 on 2023-09-28 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rundown', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='Experience')),
            ],
            options={
                'verbose_name': 'Prisoner',
                'verbose_name_plural': 'Prisoners',
            },
        ),
        migrations.CreateModel(
            name='CompletedExpeditionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_sectors', multiselectfield.db.fields.MultiSelectField(choices=[('Main', 'Main'), ('Secondary', 'Secondary'), ('Overload', 'Overload')], max_length=23, verbose_name='Cleared sectors')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rundown.expedition', verbose_name='Expedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed_expeditions',
            field=models.ManyToManyField(default=None, through='user.CompletedExpeditionUser', to='rundown.expedition', verbose_name='Completed expeditions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
