# Generated by Django 4.2.4 on 2023-09-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundown', '0003_alter_expedition_display_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_expeditions',
            field=models.ManyToManyField(default=None, to='rundown.expedition', verbose_name='Completed expeditions'),
        ),
    ]
