# Generated by Django 4.2.4 on 2023-09-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexpeditionuser',
            name='cleared_sectors',
        ),
    ]
