# Generated by Django 4.2.4 on 2023-09-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_completedexpeditionuser_cleared_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexpeditionuser',
            name='cleared_main_sector',
            field=models.BooleanField(default=True, verbose_name='Cleared main'),
        ),
        migrations.AddField(
            model_name='completedexpeditionuser',
            name='cleared_overload_sector',
            field=models.BooleanField(default=False, verbose_name='Cleared overload'),
        ),
        migrations.AddField(
            model_name='completedexpeditionuser',
            name='cleared_secondary_sector',
            field=models.BooleanField(default=False, verbose_name='Cleared secondary'),
        ),
    ]
