# Generated by Django 4.2.4 on 2023-10-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Level'),
        ),
    ]
