# Generated by Django 4.2.4 on 2023-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexpeditions',
            name='prisoner_efficiency',
            field=models.BooleanField(default=False, verbose_name='Prisoner efficiency'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
